### ISSUE TITLE
Styleflow editings

### ISSUE THREAD

**Issue by GewGaw74** [omertov/encoder4editing#13]
Thank you so much for your work.
Could you explain the next point in more detail? Step-by-step, please.

44) Note, that for Styleflow editings, 
one need to save the output latent codes and load them over the official StyleFlow repository:
torch.save(latents, 'latents.pt')

**Comment by omertov** [comment]
Hi @GewGaw74!
In the paper we present 4 editing techniques: InterFaceGAN, GANSpace, SeFa, and StyleFlow.
While I've incorporated the first 3 editing techniques into the repository, StyleFlow is currently not available as part of this repository.
In order to use the StyleFlow repository to edit your Image, you need to:
1. Invert the image into a latent code using e4e (in the notebook for example, the `latents` variable holds the inverted code.
2. Save the latent code (hence the line you mentioned, `torch.save(..)`).
3. Download the latents.pt file from the notebook environment.
4. Go to the <a href="https://github.com/RameenAbdal/StyleFlow">official StyleFlow repository</a>.
5. Use the official repo to edit the image based on the inferred latent code.
