### ISSUE TITLE
About W space?

### ISSUE THREAD

**Issue by GreenLimeSia** [omertov/encoder4editing#17]
Hi authors:
Many thanks for your excellent works. However, I have some questions about W your novel definition as follows:
What is the difference between <img src="https://latex.codecogs.com/gif.latex?\mathcal{W}^{k}&space;\text&space;{&space;and&space;}&space;\mathcal{W}_{*}^{k}" title="\mathcal{W}^{k} \text { and } \mathcal{W}_{*}^{k}" /> ?
![image](https://user-images.githubusercontent.com/28706611/115235657-01d19c00-a14d-11eb-94a1-2f2e062f4661.png)
and, In Figure. 3, I do not understand the means of the red/blue arrow. Could you kindly help me resolve this question in your spare time?

Best wishes.

**Comment by GreenLimeSia** [comment]
Could you kindly help me resolve this question in your spare time? Thanks very much.

**Comment by omertov** [comment]
Hi @GreenLimeSia!

In short, a latent code within w(k,) consists of k different style vectors, each is within the distribution of W (Which is the distrbution of style vectors produced by the mapping function given sampled z vectors from the normal distribution).
While w(k,\*) is the same as the known W+, k different style vectors without any constraints of belonging to W's distribution.

In more details:
In the paper, we discuss the distortion-perception and distortion-editability tradeoffs existing within different regions in StyleGAN's latent space.
More specifically, we show that inverting images into latent codes close to (or within) the distribution of W results in images of higher perceptual quallity and editability compared to arbitrary inversion into W+ which can achieve lower distortion.

To formalize the above, we categorize each latent code into one of 4 categories:
W(1,) - A single style vector from the distribution of W, which is fed to all style modulation layers (similar to standard SG2 generation process)
W(1,\*) - A single style vector, not strictly from the distribution of W
W(k,) - K different (unrelated) style vectors, all from the distribution of W (similar to style-mixing of sampled w codes)
W(k,\*) - K different style vectors, all of which are not strict to the distrbution of W.  (similar to W+ without restrictions)

See table 1 for a short summary:
![image](https://user-images.githubusercontent.com/51419961/115236452-0fbef700-a124-11eb-94c3-6666e693782b.png)

As a 2D visualitzation example, we conside latent codes of shape (2,1) as opposed to (18,512). 
In the above settings, a latent code in which all style vectors are equal is equivalent to points on the line y=x, and therefore it represents the w(1,\*) codes. 
In order to reach the w(1,\*) region in the latent space, one needs to travel the latent space towards the line y=x, which corresponds to the red arrow in the figure (which demonstrates our "minimizing variation" concept applied using the delta-regularization loss).

We use the heatmap to visualize the distribution of W. The red regions which are within the distribution correspond to the w(k,) region, and getting closer with each axis to the w(k,) region is indicated by the blue arrows, which correspond to the "Minimize deviation from w(k,)" principle (and to the discriminator loss).

Finally, We summarize that to get close to the w(1,) space, there is a need for both regularizations, i.e., getting closer to the regions within the distribution W (blue arrows) on the y=x line (red arrow).

Hope this clarified the figure.

**Comment by GreenLimeSia** [comment]
I am very grateful for your scrupulous explain. I will understand it carefully. Thank you for your excellent works. Thanks again!

**Comment by Booooooooooo** [comment]
> heatmap to visualize the distribution of W. The red regions which are within the distribution correspond to the w(k,)

I am trying to visualize the W space myself. How do you map the original (18,512) latent code to (2,1)?
