### ISSUE TITLE
When interpolating on the pretrained cars model, how do we specify the viewing direction?

### ISSUE THREAD

**Issue by jaymefosa** [omertov/encoder4editing#28]
Interpolating across the last dimension in the example file (0,0,5,x) doesn't spin the car quite the way we would expect.

For example in this image the latent vector at this dimension doesn't give us a 'front' view, but a mishmash.
![image](https://user-images.githubusercontent.com/92468/118392501-08343480-b675-11eb-92f4-33061959c730.png)

Any ideas?

**Comment by omertov** [comment]
Hi @jaymefosa!
Let me see if I understand correctly:
What you did was obtaining the codes of the left and right poses using GANSpace editing, and then interpolated those 2 codes to obtain a front view of the car?

If this is the case, we have also experienced this behaviour, in which as opposed the the FFHQ stylegan, the latent space of the LSUN-Cars stylegan does not yield a frontal car image once interpolated between two views of the car. 
We hypothesize that this is due to less frontal-facing car images in the LSUN-Cars dataset on which the stylegan was trained, which also explains why there is no "front" editing direction found/released by the GANSpace team.

Best,
Omer
