### ISSUE TITLE
there is something wrong in sefa editings

### ISSUE THREAD

**Issue by onefish51** [omertov/encoder4editing#51]
Hi. Thanks for your great work!

at first , I uesed the code and input image  in colab
```Python 
result1 = editor.apply_sefa(latents, indices=[2, 3, 4, 5], start_distance=0., end_distance=15.0, step=6)
result1.save('out_edit_sefa1.png')
```
![image](https://user-images.githubusercontent.com/21029719/132198960-4e0714a9-bcc8-47b4-84e7-219130cdf637.png)
emmm ,I guess it edit face in `pose` direction .

but when I changed the input image 
![image](https://user-images.githubusercontent.com/21029719/132199888-09b570dc-cba9-43a3-b441-df2893b96685.png)

it edit face in `hair style`!

Besides I want to edit face in other direction(Eyeglasses, Gender, Hair Color ...),so I changed `indices` like this :
```Python 
# indices = "0-1" #@param ['all', '0-1', '2-5', '6-13']

result = editor.apply_sefa(latents, indices=[0, 1], start_distance=0., end_distance=15.0, step=3)
result.save('out_edit_sefa.png')

result1 = editor.apply_sefa(latents, indices=[2, 3, 4, 5], start_distance=0., end_distance=15.0, step=6)
result1.save('out_edit_sefa1.png')

result2 = editor.apply_sefa(latents, indices=list(range(6, 14)), start_distance=0., end_distance=15.0, step=6)
result2.save('out_edit_sefa2.png')

result3 = editor.apply_sefa(latents, indices='all', start_distance=0, end_distance=15.0, step=6)
result3.save('out_edit_sefa3.png')
```
result :
![image](https://user-images.githubusercontent.com/21029719/132200807-fb239192-6768-4505-b1aa-7e59bc97c540.png)

![image](https://user-images.githubusercontent.com/21029719/132200862-58459eb5-593e-4580-8ef7-39b9b3524140.png)

![image](https://user-images.githubusercontent.com/21029719/132200911-d3662aa9-4252-4f00-9ce9-935e07e09ee3.png)

![image](https://user-images.githubusercontent.com/21029719/132200953-e4c265e8-24ec-4153-b9e8-198b5d13c286.png)

**Comment by omertov** [comment]
Hi @onefish51!
As SeFa decomposes the affine layers weights matrix to obtain meaningfull latent directions, they are not bound to relate to a specific semantic attribute, as opposed to the supervised methods.
for example, with InterFaceGAN you can obtain an editing direction corresponding to a specific attribute (while also being able to disentangle it from other semantic attributes based on conditioning).

It seems like the edits are inconsistent accross different latent codes (this is the issue if I understand correctly), 
so I would suggest asking your question in SeFa's repo since the implementation here should match the official one without modifications (you can test it by using the same latent codes here and in the official repo).

Best,
Omer
